name: lint, format

on:
  push:
    # branches:
    #   - main

jobs:
  rome-ci:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rome
        uses: rome/setup-rome@v0.4
        with:
          version: latest

      - name: Check Rome version
        run: rome version

      - name: Run linter & formatter
        run: rome ci .
