name: Lint, Format, Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - public/**
      - .editorconfig
      - .gitignore
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - public/**
      - .editorconfig
      - .gitignore
      - README.md

jobs:
  build:
    name: Lint, Format, Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rome
        uses: rome/setup-rome@v0.4
        with:
          version: latest

      - name: Check Rome version
        run: rome version

      - name: Run linter & formatter
        run: rome ci .

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build
